name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      workflow1Completed: true

    steps:
      - name: Step 1
        run: echo "Hello from Workflow 1"
