name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: workflow1

    steps:
      - name: Step 1
        run: echo "Hello from Workflow 2"
